CREATE TABLE USUARIO (
    ID_USUARIO int NOT NULL AUTO_INCREMENT,
    NOME varchar(255) NOT NULL,
    CPF_CNPJ varchar(14) NOT NULL,
    TIPO_PESSOA varchar(20),
    EMAIL varchar(100),
    TELEFONE double,
    PRIMARY KEY (ID_USUARIO)
);

select * from USUARIO;

CREATE TABLE PEDIDO (
	PEDIDO_GUID varchar(500) NOT NULL,
	CREATE_DATE DATE NOT NULL,
	LAST_UPDATE_DATE DATE, 
	SITUACAO CHAR,
	ID_USUARIO int NOT NULL,
	PRIMARY KEY (PEDIDO_GUID),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);


SELECT * FROM PEDIDO;